# Page settings
baseurl = "namir.onrender.com"
title = "NAMIR"
languageCode = "pt-br"
theme = "hugo-elate"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = "f/xdopdbrp"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "NAMIR"
    home = "Home"
    work = "Atividades em andamento"
    testimonials = "Testemunhos"
    services = "Organização"
    about = "Sobre"
    contact = "Contato"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Núcle de Apoio ao Migrante e Refugiado"
    subtitle = 'Programa de extensão da Universidade Federal da Bahia.'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  # [params.intro]

  # [[params.intro.item]]
  #   title = "Objetivo"
  #   description = "Colocar objetivo."
  #   url = "#"
  #   # button = "Get In Touch"
  #   icon = "icon-bulb"
  #   img = "img_7.jpg"

  # [[params.intro.item]]
  #   title = "Missão"
  #   description = "Atenção à saúde."
  #   url = "#"
  #   # button = "Click Me"
  #   icon = "icon-wrench"
  #   img = "img_8.jpg"

  # [[params.intro.item]]
  #   title = "Valores"
  #   description = "Treinamentos e oficinas culturais."
  #   url = "#"
  #   # button = "Why us?"
  #   icon = "icon-rocket"
  #   img = "img_10.jpg"


  # [params.intro.video]
  #   enable = false
  #   title = "Watch the video"
  #   icon = "icon-play2"
  #   url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Atividades em andamento"
    description = "Atvidades de extensão promovidas ou apoiadas pelo NAMIR-UFBA."
    # footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "cartaz-oficina-curriculo.png"
      alt = "Image2"
      title = "Oficina de Currículo"
      subtitle = "Comissão de Trabalho e Políticas Sociais"

    [[params.work.row]]
      img = "logo-namir.jpg"
      alt = "Image2"
      title = "Curso de capacitação"
      subtitle = "Comissão de Direitos Humanos"

    # [[params.work.row]]
    #   img = "work_3.jpg"
    #   alt = "Image3"
    #   title = "Project 3"
    #   subtitle = "Design"

    # [[params.work.row]]
    #   img = "work_4.jpg"
    #   alt = "Image4"
    #   title = "Project 4"
    #   subtitle = "Design"

    # [[params.work.row]]
    #   img = "work_5.jpg"
    #   alt = "Image5"
    #   title = "Project 5"
    #   subtitle = "Design"

    # [[params.work.row]]
    #   img = "work_6.jpg"
    #   alt = "Image6"
    #   title = "Project 6"
    #   subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = true
    title = "Missão e valores"
    description = "O NAMIR é organizado em comissões com missões e valores específicos."

    [[params.services.item]]
      title = "Comissão de Educação"
      description = "Descrição das atividades da Comissão de Educação."
      # icon = "icon-anchor"

    [[params.services.item]]
      title = "Comissão de Direitos Humanos"
      description = "Descrição das atividades da Comissão de Direitos Humanos"
      # icon = "icon-layers2"

    [[params.services.item]]
      title = "Comissão de Trabalho e Políticas Sociais"
      description = "Descrição das atividades da Comissão de Trabalho e Políticas Sociais"
      # icon = "icon-video2"

      [[params.services.item]]
      title = "Comissão de Saúde"
      description = "Descrição das atividades da Comissão de Saúde"      
      # icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "Sobre o NAMIR"
    description = "Abaixo listamos a nossa equipe."

    [[params.about.item]]
      name = "Roberto Santana"
      position = "Voluntário"
      description = "Docente do Instituto de Matemática e Estatística da UFBA."
      # img = "person1.jpg"
      # alt = "Person1"
      social = [
        ["icon-instagram", "#"],
        ["icon-facebook", "#"]
      ]

    [[params.about.item]]
      name = "Gilberto Sassi"
      position = "Voluntário"
      description = "Docente do Instituto de Matemática e Estatística da UFBA."
      # img = "person2.jpg"
      # alt = "Person2"
      social = [
        ["icon-instagram", "#"],
        ["icon-facebook", "#"]
      ]

    [[params.about.item]]
      name = "Cristina Lizana"
      position = "Coordenadora Geral"
      description = "Docente do Instituto de Matemática e Estatística da UFBA.."
      # img = "person3.jpg"
      # alt = "Person3"
      social = [
        ["icon-instagram", "#"],
        ["icon-facebook", "#"]
      ]      

  # # Counters section
  # [params.counters]
  #   enable = true
  #   title = "Stats"
  #   background = "full_image_1.jpg"

  #   [[params.counters.item]]
  #     description = "Finished projects"
  #     icon = "icon-briefcase"
  #     from = 0
  #     to = 89
  #     interval = 50
  #     speed = 5000

  #   [[params.counters.item]]
  #     description = "Lines of code"
  #     icon = "icon-code"
  #     from = 0
  #     to = 2343409
  #     interval = 50
  #     speed = 5000

  #   [[params.counters.item]]
  #     description = "Cups of coffee"
  #     icon = "icon-cup"
  #     from = 0
  #     to = 1302
  #     interval = 50
  #     speed = 5000

  #   [[params.counters.item]]
  #     description = "Happy clients"
  #     icon = "icon-people"
  #     from = 0
  #     to = 52
  #     interval = 50
  #     speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Entre em contato"
    description = "Sinta-se a vontade para entrar em contato conosco."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Universidade Federal da Bahia -- Rua Augusto Viana, s/n - Palácio da Reitoria, Canela, Salvador - CEP: 40110-909"],
        ["icon-phone", "A definir"],
        ["icon-envelope", "namirufba@ufba.br"]
      ]

    name = "Nome"
    email = "Email"
    phone = "(99)9999-9999"
    message = "Mensagem"
    button = "Enviar"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy;  NAMIR 2020'
    links = [
        ["icon-instagram", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
